---
apiVersion: v1
kind: Service
metadata:
  name: kafka-np
  labels:
    name: kafka-np
spec:
  ports:
  - port: 30092
    name: kafka-np
    targetPort: 30092
    protocol: TCP
    nodePort: 30092
  selector:
    app: kafka
  type: NodePort


